name: Lint & Typecheck

on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd frontend && npx run lint
      - run: cd frontend && npx run typecheck

  backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd backend && npx run lint
      - run: cd backend && npx run typecheck
