name: Lint & Typecheck

on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # or whatever version you use (e.g. 8.x if older)
          run_install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm tsc --version
      - run: pnpm run typecheck

  backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # or whatever version you use (e.g. 8.x if older)
          run_install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm tsc --version
      - run: pnpm run typecheck
